### ISSUE TITLE
Blocks that require a pickacxe don't drop anything

### ISSUE THREAD

**Issue by Munsterlandr** [Filostorm/Multiblock-Madness-2#11]
Even when using a pickaxe, stone (and other blocks that should be mined with a pickaxe) drop nothing, and mines at the same speed as it would be when using my hands. Also, The One Probe shows this:
![2023-04-29_20 23 57](https://user-images.githubusercontent.com/81447509/235332577-b78ae453-419c-44eb-bac4-3f3a183a40af.png)

Is this an intentional mechanic I'm just missing, or is it bugged?

**Comment by Filostorm** [comment]
Definitely bugged. It seems like sometimes tags might be messed up.  

Can you send your logs?

What launcher are you using?

**Comment by Munsterlandr** [comment]
I'm using Prism Launcher on the linux distro KDE Neon with openjdk 17. I also had installed 2 extra mods, those being _Ears_ and _Damage Tilt_. I've not found issues being caused by them in the past, but just in case, I ran a fresh instance of the pack without them and got the logs from that [right here](https://mclo.gs/1iaSXi4). The bug is still present without them.

**Comment by Filostorm** [comment]
This has been narrowed down to the mod Excavated Variants. Feel free to post there and we can see if its able to be resolved [**https://github.com/lukebemish/ExcavatedVariants/issues**](https://github.com/lukebemish/ExcavatedVariants/issues)

**Comment by Filostorm** [comment]
Issue has been found, and will be fixed in the next update.

**Comment by Munsterlandr** [comment]
i am still experiencing this issue.

**Comment by Filostorm** [comment]
I reset the cashe again in 0.4.1, so hopefully its fixed again
