### ISSUE TITLE
Raw ores can no longer be smelted after 1.20 update.

### ISSUE THREAD

**Issue by wilsnat** [Filostorm/Multiblock-Madness-2#13]
Raw ores can no longer be smelted after the latest update and the traditional recipe is gone. They can be processed and then smelted but I don't believe that was intended and the original recipe was to remain but allow for additional processing steps. For example, freshly mined Raw_Iron cannot be used in a furnace to create the ingot.

Does not smelt despite tooltip.
![image](https://github.com/Filostorm/Multiblock-Madness-2/assets/5231181/3922f742-48d2-479d-a73f-32aa800fa64b)
![image](https://github.com/Filostorm/Multiblock-Madness-2/assets/5231181/efa1e82c-2797-4ffa-ac44-340c0d841c1d)
Here are the smeltable copper tiers for an copper ingot. Raw copper is not available.
![image](https://github.com/Filostorm/Multiblock-Madness-2/assets/5231181/056f3cd4-af98-43af-98a1-2eef76f72f54)

I'm a little past the first chapter and I think this might make the game impossible for anyone just starting.

**Comment by Filostorm** [comment]
Yeah this is pretty major lol. Fixed in 0.2.1
