### ISSUE TITLE
Broken precision mechanism recipe

### ISSUE THREAD

**Issue by caid101** [Filostorm/Multiblock-Madness-2#15]
The precision mechanism recipe in the engineer's workbench has an empty tag.
![2023-06-16_20 00 53](https://github.com/Filostorm/Multiblock-Madness-2/assets/46058138/912b88fb-aa0c-42be-a550-75541a284eb5)

**Comment by Filostorm** [comment]
Will be fixed in 0.2.2, thanks for the report!
