### ISSUE TITLE
in multiplayer raw iron can't be smelted into iron ingot

### ISSUE THREAD

**Issue by Frefreak** [Filostorm/Multiblock-Madness-2#18]
Hi, this which seems to be caused by the missing of `global.refiningMultiplier` here:

https://github.com/Filostorm/Multiblock-Madness-2/blob/3c14e4c58947cf763aa878bed52739ee5079932b/kubejs/server_scripts/ore_processing.js#L364

`global.refiningMultiplier` appears only inside client_scripts
https://github.com/Filostorm/Multiblock-Madness-2/blob/3c14e4c58947cf763aa878bed52739ee5079932b/kubejs/client_scripts/material_tooltips.js#L66-L74

adding this into `server_scripts/global.js` makes the recipe works and no more kubejs errors when logging into the server.

**Comment by Filostorm** [comment]
Good to know, thanks! Will be fixed soon
