### ISSUE TITLE
Steel is currently unobtainable, entirely preventing progression halfway through chapter 2.

### ISSUE THREAD

**Issue by Mojo450wastaken** [Filostorm/Multiblock-Madness-2#20]
Steel is currently unobtainable, as the Immersive Engineering blast furnace and the Tinkers' Construct Foundry both require tough bricks. Tough bricks in turn require molten slag. Slag can be obtained, but the only ways of melting it currently are the Tinkers' Construct Foundry and the Tinkers' Construct Smeltery. The Smeltery Controller requires a steel gear to craft. Thus, in order to obtain steel, you need to have already obtained steel.

**Comment by Filostorm** [comment]
The steel paradox

**Comment by Filostorm** [comment]
Actually, can you melt slag in the melter? Either way I'll smooth this out

**Comment by Mojo450wastaken** [comment]
REI lists slag's melting point as 900 degrees, which I believe is higher than the melter can reach.

**Comment by Filostorm** [comment]
You're able to use a tank with lace to reach 1000
