### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by 821399289** [Filostorm/Multiblock-Madness-2#21]
I had a client crash while using Part 
[Uploading crash-2023-07-30_22.55.02-client.txt…]()

**Comment by 821399289** [comment]
[crash-2023-07-30_22.55.02-client.txt](https://github.com/Filostorm/Multiblock-Madness-2/files/12209523/crash-2023-07-30_22.55.02-client.txt)

**Comment by 821399289** [comment]
[crash-2023-07-30_22.55.02-client.txt](https://github.com/Filostorm/Multiblock-Madness-2/files/12209525/crash-2023-07-30_22.55.02-client.txt)

**Comment by Filostorm** [comment]
What item crashes you?

**Comment by 821399289** [comment]
Part Builder in Tinkers' Construct 3, I move and crash while filling material

**Comment by 821399289** [comment]
This is a very serious problem, I hope you can pay attention to it

**Comment by 821399289** [comment]
Unfortunately, I encountered the crash error again, and it also crashed when opening the backpack inventory

**Comment by Filostorm** [comment]
Should be fixed in 0.4.0
