### ISSUE TITLE
Crash Joining server running version .52 with client version .52 

### ISSUE THREAD

**Issue by Gurtygurt98** [Filostorm/Multiblock-Madness-2#25]
Hello, 

After joining a server with a client of the same version I recieve the following error message. 
![image](https://github.com/Filostorm/Multiblock-Madness-2/assets/81448848/cc33ac78-44cf-4462-a13d-818003d738dd)

**Comment by Filostorm** [comment]
That's a config conflict for that mod. How was the server updated?

**Comment by Gurtygurt98** [comment]
The server was updated using the server file download on curseforge
desktop.

**Comment by Gurtygurt98** [comment]
Just to add this is a new install of this modpack on the server not an update.

**Comment by Filostorm** [comment]
can you send the log from your server and client?

**Comment by Gurtygurt98** [comment]
Will do. I will have to wait for the server operator to send me over the logs.

**Comment by Gurtygurt98** [comment]
[debug.log.txt](https://github.com/Filostorm/Multiblock-Madness-2/files/12654318/debug.log.txt)
[client_log_-_Copy.txt](https://github.com/Filostorm/Multiblock-Madness-2/files/12654319/client_log_-_Copy.txt)
See attached logs

**Comment by Gurtygurt98** [comment]
Just as an update on this issue. Removing the config for Excavated Variants allowed us to join the server but after adding it back we get the same error.

**Comment by Filostorm** [comment]
Not sure why but these seem to be the issue:
[18:27:45] [Render thread/ERROR]: Unidentified mapping from registry minecraft:block
	excavated_variants:basalt_ancient_debris_ore: 9532
	excavated_variants:basalt_nether_gold_ore: 9115
	excavated_variants:blackstone_ancient_debris_ore: 9533
	excavated_variants:blackstone_nether_gold_ore: 9116

[18:27:45] [Render thread/ERROR]: Unidentified mapping from registry minecraft:item
	excavated_variants:basalt_ancient_debris_ore: 10152
	excavated_variants:basalt_nether_gold_ore: 9735
	excavated_variants:blackstone_ancient_debris_ore: 10153
	excavated_variants:blackstone_nether_gold_ore: 9736
