### ISSUE TITLE
Two outputs for smelting enderpearls in the smeltery

### ISSUE THREAD

**Issue by Konhaiii** [Filostorm/Multiblock-Madness-2#35]
In JEI there is two crafts in the smeltery from TConstruct for the enderpearl. One is giving Molten Ender wich is useless, and the other gives Resonant Ender. Sadly, the effective in-game ouput is the Molten Ender, so puting enderpearls in the smeltery is currently broken.

Edit: Seems you forgot "ender" in the tconstruct recipe directory in unify.js :

`	  event.custom({
		"type": "tconstruct:melting",
		"ingredient": [
		  {
			"tag": "forge:ender_pearls"
		  },
		  {
			"item": "minecraft:ender_eye"
		  }
		],
		"result": {
		  "fluid": "thermal:ender",
		  "amount": 250
		},
		"temperature": 477,
		"time": 49
	  }).id('tconstruct:smeltery/melting/ender/pearl')`

**Comment by Filostorm** [comment]
Fixed in 0.5.5, Ty for the report!
