### ISSUE TITLE
The Arc Furnace is unable to output

### ISSUE THREAD

**Issue by 1hsnet** [Filostorm/Multiblock-Madness-2#45]
The Arc Furnace in Immersive Engineering seems unable to output, whatever using item pipe in pipez or ME import bus in AE2.

**Comment by Filostorm** [comment]
I believe the arc furnace needs an inventory to export into. So an interface should do the trick for your needs

**Comment by 1hsnet** [comment]
Yeah, and it doesn't work.

**Comment by Filostorm** [comment]
Did you figure it out?

**Comment by 1hsnet** [comment]
No doubt. I just figured it out when I accidentally put a crafter tier next to another output end of the arc furnace, locating right on the other side of the output end where it should be, then uranium ingot in the arc furnace import into the crafter tier. Actually, I didn't realize that some machines in Immersive engineering only interacts with chests but not the pipes, such as excavator and crusher, but two machines above have no gui, which is not like this on the arc furnace, so I still feel kind of weird.
