### ISSUE TITLE
Refined Pipes show no crafting recipes

### ISSUE THREAD

**Issue by 1hsnet** [Filostorm/Multiblock-Madness-2#48]

**Comment by Filostorm** [comment]
Correct, the mod is being removed in the next update

**Comment by 1hsnet** [comment]
Is this because other pipes already exist, making the refined pipes appear redundant?

**Comment by Filostorm** [comment]
The primary reason is because there is texture glitches, but it's also pretty mediocre compared to pipez imo

**Comment by 1hsnet** [comment]
ur right, I'm a pipez enjoyer lol
