### ISSUE TITLE
Mbm2 exists texture glitches

### ISSUE THREAD

**Issue by 1hsnet** [Filostorm/Multiblock-Madness-2#49]
Sometimes multiblock structures unique to your pack show texture glitches,  manifested as textures swapping between item output bus and mk1 energy input or bluring to white.
Corresponding resource packs show them made for an older version.
![Snipaste_2024-03-03_11-20-46](https://github.com/Filostorm/Multiblock-Madness-2/assets/161273804/7b51ecd1-c6fa-47a1-8dc0-681070d22934)

**Comment by Filostorm** [comment]
Sadly I'm not sure if this will ever get fixed
