### ISSUE TITLE
Silk Touch problems

### ISSUE THREAD

**Issue by erkiff** [Filostorm/Multiblock-Madness-2#5]
Hi! I like this pack and I'm having lots of fun, even though it's not done yet. However, I'm noticing some issues using Silk Touch on certain blocks. I've tried the Extract modifier from Ars Noveau and the Silky modifier from Tinker's, not a vanilla enchant, so that could be contributing. 
The craziest issue I've encountered is that Deepslate Copper blocks still drop raw ore. However, most of the issues are with the custom added blocks. The elemental ores don't seem to be silk-able, which is a shame since they can drop 3 different things. It's the same with poor ores and the arcanite (and I'm assuming compound) ores.
I also cannot silk touch spawners, instead I always get the broken spawner from Spirit. Is this intentional?
Thank you for making this pack, keep up the good work!

**Comment by Filostorm** [comment]
Not being able to silk touch, spawners is intentional, the rest is not. Thanks for reporting!

**Comment by Filostorm** [comment]
The reason for this is how I'm adding the drops to the ores through kubejs, including making copper ore only drop one raw instead of 2-5 or whatever vanilla is. I'm not sure exactly what the fix is, but I'll try doing it through LootJS eventually
