### ISSUE TITLE
Obstacles in auto-crafting containing both fluids and items

### ISSUE THREAD

**Issue by 1hsnet** [Filostorm/Multiblock-Madness-2#50]
Herbicide could be produced through the mixer in Immersive Engineering which needs mixing ethanol with some dusts, but the ME pattern provider seems unable to provide fluids and items at the same time. Maybe we need [ae2fc].

**Comment by Filostorm** [comment]
The issue is you need the fluids and items in separate places when you are automating Herbicide. A possible solution would be passivizing the ethanol and just putting the copper and sulfur dusts in the recipe

**Comment by 1hsnet** [comment]
You mean that I need to manually craft fluid so that I can avoid this conflict

**Comment by Filostorm** [comment]
I'm saying the way AE works is when you run a pattern, all the inputs must be inserted into the same place. Since this isn't how it works with IE multiblocks, it can't work
