### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by 1hsnet** [Filostorm/Multiblock-Madness-2#51]
I met a crash while using fluiduct (windowed) in thermal series.
[2024-03-06-3.log](https://github.com/Filostorm/Multiblock-Madness-2/files/14509429/2024-03-06-3.log)

**Comment by Filostorm** [comment]
what were you using them for?

**Comment by Filostorm** [comment]
Not sure if I can help with this:
`Caused by: java.lang.NullPointerException: Cannot invoke "cofh.thermal.dynamics.grid.Grid.getNodes()" because the return value of "cofh.thermal.dynamics.api.grid.IDuct.getGrid()" is null`

**Comment by 1hsnet** [comment]
I was using them for connecting fluid cell containing liquid sodium with fliud tank in IE.

**Comment by 1hsnet** [comment]
Actually I was using crescent hammer to change block states of fluiduct (windowed) at that time.

**Comment by 1hsnet** [comment]
Never mind, I have loaded the backup, and everything is fine at present.
