### ISSUE TITLE
May i find some bugs?

### ISSUE THREAD

**Issue by Shengxiaomoyu-ForesT** [Filostorm/Multiblock-Madness-2#6]
I can't mine the stone or some kinds of ores. Is it uncommon or the settings of modpack?

**Comment by Filostorm** [comment]
Assuming you are referring to veinminer/ore excavator, that is an intentional choice to blacklist ores and stone

**Comment by wrighs6** [comment]
I don't know if this is the same issue, but I can't mine stone (or other pickaxe-breakable blocks) at all. I tried with a vanilla stone pick and a tinker's flint pick, with both it took a long time to break and dropped no item. I'm using the Prism launcher on Linux, if that helps.

**Comment by Filostorm** [comment]
That is very strange, how did you get the stone in the first place?

**Comment by wrighs6** [comment]
I crafted the stone pick with flint

**Comment by Filostorm** [comment]
Same issue as #11 - Fixed
