### ISSUE TITLE
Crash on launch after update to 0.7.2

### ISSUE THREAD

**Issue by DiegoRutolo** [Filostorm/Multiblock-Madness-2#64]
After updating instance on ATLauncher from 0.7.1 to 0.7.2 it chashes on launch, saying the Ferruchemy mod failed to load.

The game can be launched by manualy disabling the mod, so it may be a issue with the launcher, not the pack.

**Comment by TigerWalts** [comment]
The Feruchemy mod requires Allomancy which is missing in version `0.7.2` of the pack.

**Comment by Filostorm** [comment]
Somehow the mod list manifest got mixed up with an earlier version of the pack (I think), should be fixed in 0.7.2b
