### ISSUE TITLE
Multiblock machines negative time remaining

### ISSUE THREAD

**Issue by DiegoRutolo** [Filostorm/Multiblock-Madness-2#66]
When a multiblock machine loses power, the time remaining can go into negatives, and when it gets power againg, the number keeps decreasing, consuming power but never finishing.

![2024-05-27_21 47 49](https://github.com/Filostorm/Multiblock-Madness-2/assets/32809544/8a3bbc67-2b6a-4c5a-acfc-1a4d864e920a)

For the moment it happened with Electric blast furnace and Flotation tank.

I'm not sure how this machines are implemented, so if they are from another mod, please let me know and i'll report it there.

**Comment by Filostorm** [comment]
It's from Multiblocked, hopefully that'll be fixed, it's pretty unlikely the mod gets updated soon

**Comment by DiegoRutolo** [comment]
https://github.com/CleanroomMC/Multiblocked/issues/104

Alright, i've reported this in the mod, you can close this issue. thank you.

**Comment by Filostorm** [comment]
Great, thanks!
