### ISSUE TITLE
Can't complete the quest "Washed Ores (2x)"

### ISSUE THREAD

**Issue by cath01iq** [Filostorm/Multiblock-Madness-2#67]
In "Ore Processing" questline, cannot complete the quest "Washed Ores (2x)".
It seems crushed ores are not washed into washed form of it, but dusts and some extra grits and gravel.
![2024-05-31_15 48 30](https://github.com/Filostorm/Multiblock-Madness-2/assets/99516947/b09dafb7-52ba-43f4-a561-43010f5b1577)

**Comment by Filostorm** [comment]
Fixed
