### ISSUE TITLE
pyrotheum dust Recipe Questions

### ISSUE THREAD

**Issue by xiaodou233333** [Filostorm/Multiblock-Madness-2#69]
When using an industrial mixer to make pyrotheum_dust, blazing_redstone is now made first.
![image](https://github.com/Filostorm/Multiblock-Madness-2/assets/61956441/d785e0ba-d08a-404a-9297-27c93d2d1b21)

**Comment by Filostorm** [comment]
Thanks for reminding me about this, I'll fix it in the next update

**Comment by Filostorm** [comment]
Fixed
