### ISSUE TITLE
工业搅拌机加入流体没有可以加流体的地方

### ISSUE THREAD

**Issue by UnthinkingBrain** [Filostorm/Multiblock-Madness-2#71]
在生产信素粉、流明粉、末影粉的时候需要向工业搅拌机加入流体，但是此多方块没有可以加流体的地方

**Comment by Filostorm** [comment]
You should be able to replace any casing block with a fluid input hatch

**Comment by UnthinkingBrain** [comment]
> 您应该能够用流体输入舱口替换任何套管块

OK，I will try it and feel your response
