### ISSUE TITLE
Empty Tag in "Arboreal Extractor" recipe

### ISSUE THREAD

**Issue by iasazo** [Filostorm/Multiblock-Madness-2#9]
The recipe for the "arboreal extractor" is broken.  It requires an item with the tag "forge:cogwheels" but claims that that tag is empty.  This makes the item uncraftable.

**Comment by BenFan1002** [comment]
You can temporarily fix this by change .minecraft\versions\MBM18\kubejs\server_scripts\mod_scripts\thermal.js the follwoing in 
event.shaped('thermal:device_tree_extractor', [
	'ABA',
	'CDC',
	'AEA'
  ], {
	A: '#minecraft:planks',
	B: '#forge:gears/copper',
	C: '#extendedgears:cogwheel', // changed this line from forge:cogwheels to this
	D: 'thermal:redstone_servo',
	E: 'minecraft:bucket'
  }).id("mbm2:device_tree_extractor")

**Comment by Filostorm** [comment]
Fixed in 0.1.8
